### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by DeepGreenAI**
This pull requests implements all of the suggestions from the candy machine audit report by ottersec/Ape16z for the `metaplex-foundation/sugar` repo. A more detailed explanation of the changes in this PR can be found here: https://docsend.com/view/is7963h8tbbvp2g9.

Changes to `src/deploy/process.rs`:
* refactor unnecessary error handling

Changes to` src/upload/assets.rs`:
* remove unused struct definition
* verify that filename arrays contain exactly one element

Changes to `src/upload/process.rs`:
* simplify the logging

### CODE REVIEW

**Comment by samuelvanderwaal** [comment]
@DeepGreenAI thanks so much for the PR! If you can fix the clippy lint issues I'll approve and merge.

**Comment by samuelvanderwaal** [comment]
To fix the remaining issue, just run `cargo fmt` and commit the formatting changes.

**Comment by DeepGreenAI** [comment]
> To fix the remaining issue, just run `cargo fmt` and commit the formatting changes.

Done, thanks!

**Comment by samuelvanderwaal** [comment]
Thanks so much!

**Review by samuelvanderwaal — APPROVED** [review]

**Pull request merged**
