### PR TITLE
Continuous series check

### PR DESCRIPTION
**Pull request by ohaddahan**
Adding a check that the assets are a continuous series `0.json`, `1.json` ... `N.json`.

Need some instructions on the testing, want to add couple of tests that cover:

1. Proper series.
2. Missing item.
3. Duplicate item.
4. Out of range item (`N+X.json` but only `N` items in directory).

Code now should support these cases, but need to confirm via tests.

### CODE REVIEW

**Comment by samuelvanderwaal** [comment]
One approach for testing:

Create a `tests` folder and then `assets/continous` within that and create some empty json files sequentially numbered.

Screen Shot 2022-09-26 at 7 43 03 PM

Then write a unit test against that in the `validate/process.rs` file:

```rust
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_validate_continuous_assets() {
        let result = process_validate(ValidateArgs {
            assets_dir: "tests/assets/continuous".to_string(),
            strict: false,
            skip_collection_prompt: true,
        });
        assert!(result.is_ok());
    }
}
```

You can do similar for `redundant`, `proper`, `missing-item` cases, by having separate folders with assets, like `tests/assets/missing-item` etc. and adding more unit tests within the test module.

**Comment by samuelvanderwaal** [comment]
Another way would be to extract the code for testing the series to a separate function that takes a list of paths as an input instead of an assets directory, then you can unit test that more easily by just creating the lists of paths you want to use:

```rust
#[test]
 fn test_validate_continuous_assets() {
        let continuous = vec!["0.json", "1.json", "2.json", "3.json", "4.json"];
        
        assert!(validate_num_series(continous).is_ok());
 }
```

Something like that.

**Comment by ohaddahan** [comment]
> Another way would be to extract the code for testing the series to a separate function that takes a list of paths as an input instead of an assets directory, then you can unit test that more easily by just creating the lists of paths you want to use:
> 
> ```rust
> #[test]
>  fn test_validate_continuous_assets() {
>         let continuous = vec!["0.json", "1.json", "2.json", "3.json", "4.json"];
>         
>         assert!(validate_num_series(continous).is_ok());
>  }
> ```
> 
> Something like that.

Wanted to write it in functions but the styling was flat so didn't want to mess with it :)

**Comment by samuelvanderwaal** [comment]
> > Another way would be to extract the code for testing the series to a separate function that takes a list of paths as an input instead of an assets directory, then you can unit test that more easily by just creating the lists of paths you want to use:
> > ```rust
> > #[test]
> >  fn test_validate_continuous_assets() {
> >         let continuous = vec!["0.json", "1.json", "2.json", "3.json", "4.json"];
> >         
> >         assert!(validate_num_series(continous).is_ok());
> >  }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Something like that.
> 
> Wanted to write it in functions but the styling was flat so didn't want to mess with it :)

If you prefer that, go for it! As long as the Sugar messages stay reasonably consistent you can break validate down into whatever smaller pieces pleases you.

**Comment by ohaddahan** [comment]
Added few tests, was unable to cover only one error message (happy path works)

(removed this test for now since it doesn't fail with the expected error)

```rust
#[test]
fn test_validate_continuous_assets_fail_missing() {
    let paths = vec![
        PathBuf::from("assets/0.json"),
        PathBuf::from("assets/2.json"),
        PathBuf::from("assets/3.json"),
        PathBuf::from("assets/4.json"),
        PathBuf::from("assets/collection.json"),
    ];
    let result = validate_continuous_assets(&paths);
    assert!(result.is_err());
    assert_eq!(result.unwrap_err().to_string(), "Assets list isn't continuous please check files");
}
```

Seems like all the other validations catch before we can ever get to:

```rust
if sum != target_sum {
        return Err(ValidateParserError::NonContinuousSeries.into());
    }
```

Not sure if it's critical, since happy path is validated and quite a few bad cases are no covered.
Error phrasing, can probably be improved.

**Comment by ohaddahan** [comment]
Ready for review @samuelvanderwaal

**Comment by samuelvanderwaal** [comment]
> 

Yeah, the `File out of range` error basically is the `Not continuous error` so this test is probably redundant. 

I think this all good and the fact that you actually have tests is super nice as we don't have many in the code base. 

It might be nice to add a test to check a completely empty assets folder, although that might actually be caught by a different validator elsewhere in Sugar.

```Rust
#[test]
fn test_validate_continuous_assets_fail_no_paths_found() {
    let paths = vec![];
    let result = validate_continuous_assets(&paths);
    assert!(result.is_err());
    assert_eq!(
        result.unwrap_err().to_string(),
        "No assets found in assets directory"
    );
}
```

Otherwise, this looks good and I'll approve it. Thanks so much for the PR!

**Review by samuelvanderwaal — APPROVED** [review]

**Comment by samuelvanderwaal** [comment]
Looks like an empty assets dir [is caught here](https://github.com/metaplex-foundation/sugar/blob/29d4002b74777ac630f25f4e8c47160cc76ace07/src/validate/process.rs#L32) so need for that last test I suggested.

**Pull request merged**
